### ISSUE TITLE
License?

### ISSUE THREAD

**Issue by tobiasherp** [hans-sperling/urlSplit.js#1]
Under which license can this nice tool be used?
I'd like to use it in a GPLv2+ project ([visaplan.plone.ajaxnavigation](https://github.com/visaplan/plone.ajaxnavigation)); instead of integrating it in my project, I could create a simple Plone integration.

**Comment by hans-sperling** [comment]
I added a license file to this prokect. It's now under MIT.

**Comment by tobiasherp** [comment]
Perfect -- thank you!
